"""initial schema

Revision ID: c4724ba63c75
Revises: 
Create Date: 2026-09-12 22:30:38.891758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4724ba63c75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_event_id', sa.String(length=160), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('payload_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_billing_event_provider_id')
    )
    op.create_index(op.f('ix_billing_events_provider_event_id'), 'billing_events', ['provider_event_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=40), nullable=False),
    sa.Column('subscription_status', sa.String(length=40), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_customer_id', sa.String(length=120), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=120), nullable=False),
    sa.Column('provider_price_id', sa.String(length=120), nullable=False),
    sa.Column('plan', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subscription_id', name='uq_subscription_provider_id')
    )
    op.create_index(op.f('ix_subscriptions_provider_customer_id'), 'subscriptions', ['provider_customer_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_provider_subscription_id'), 'subscriptions', ['provider_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_index(op.f('ix_workspaces_user_id'), 'workspaces', ['user_id'], unique=False)
    op.create_table('company_evidence_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.String(length=80), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_company_evidence_documents_workspace_id'), 'company_evidence_documents', ['workspace_id'], unique=False)
    op.create_table('company_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=240), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_type', sa.String(length=160), nullable=True),
    sa.Column('industry', sa.String(length=160), nullable=True),
    sa.Column('years_in_business', sa.Integer(), nullable=True),
    sa.Column('main_services', sa.Text(), nullable=True),
    sa.Column('areas_of_expertise', sa.Text(), nullable=True),
    sa.Column('relevant_licences', sa.Text(), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('registrations', sa.Text(), nullable=True),
    sa.Column('bca_registration_info', sa.Text(), nullable=True),
    sa.Column('past_project_experience', sa.Text(), nullable=True),
    sa.Column('typical_project_size', sa.String(length=160), nullable=True),
    sa.Column('maximum_project_size', sa.String(length=160), nullable=True),
    sa.Column('geographic_coverage', sa.Text(), nullable=True),
    sa.Column('number_of_employees', sa.Integer(), nullable=True),
    sa.Column('key_capabilities', sa.Text(), nullable=True),
    sa.Column('insurance_coverage', sa.Text(), nullable=True),
    sa.Column('other_qualifications', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profiles_workspace_id'), 'company_profiles', ['workspace_id'], unique=True)
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('organization', sa.String(length=240), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_file_name', sa.String(length=255), nullable=False),
    sa.Column('analysis_status', sa.String(length=30), nullable=False),
    sa.Column('analysis_error', sa.Text(), nullable=True),
    sa.Column('analysis_started_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_completed_at', sa.DateTime(), nullable=True),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.Column('analysis_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_file_name')
    )
    op.create_index(op.f('ix_tenders_workspace_id'), 'tenders', ['workspace_id'], unique=False)
    op.create_table('bid_workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('workflow_status', sa.String(length=30), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_workspaces_tender_id'), 'bid_workspaces', ['tender_id'], unique=True)
    op.create_table('company_evidence_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(length=80), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['company_evidence_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_evidence_chunks_document_id'), 'company_evidence_chunks', ['document_id'], unique=False)
    op.create_table('tender_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('company_profile_version', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_assessments_tender_id'), 'tender_assessments', ['tender_id'], unique=False)
    op.create_table('tender_checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_snippet', sa.Text(), nullable=True),
    sa.Column('evidence_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_checklist_items_tender_id'), 'tender_checklist_items', ['tender_id'], unique=False)
    op.create_table('tender_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=120), nullable=False),
    sa.Column('date_value', sa.String(length=80), nullable=False),
    sa.Column('time_value', sa.String(length=40), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_snippet', sa.Text(), nullable=True),
    sa.Column('evidence_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_snippet', sa.Text(), nullable=True),
    sa.Column('evidence_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('evidence_type', sa.String(length=20), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_snippet', sa.Text(), nullable=True),
    sa.Column('evidence_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(length=80), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('retrieval_method', sa.String(length=30), nullable=True),
    sa.Column('embedding_ref', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('tender_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('usage_type', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_created_at'), 'usage_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_events_tender_id'), 'usage_events', ['tender_id'], unique=False)
    op.create_index(op.f('ix_usage_events_user_id'), 'usage_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_usage_events_workspace_id'), 'usage_events', ['workspace_id'], unique=False)
    op.create_table('bid_clarifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['tender_questions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['bid_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_index(op.f('ix_bid_clarifications_workspace_id'), 'bid_clarifications', ['workspace_id'], unique=False)
    op.create_table('bid_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('tender_document_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tender_document_id'], ['tender_documents.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['bid_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_document_id')
    )
    op.create_index(op.f('ix_bid_documents_workspace_id'), 'bid_documents', ['workspace_id'], unique=False)
    op.create_table('bid_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['bid_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_notes_workspace_id'), 'bid_notes', ['workspace_id'], unique=False)
    op.create_table('bid_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['bid_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_packages_workspace_id'), 'bid_packages', ['workspace_id'], unique=True)
    op.create_table('bid_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['tender_requirements.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['bid_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id')
    )
    op.create_index(op.f('ix_bid_requirements_workspace_id'), 'bid_requirements', ['workspace_id'], unique=False)
    op.create_table('tender_bid_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_snippet', sa.Text(), nullable=True),
    sa.Column('company_field', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['tender_assessments.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_bid_actions_assessment_id'), 'tender_bid_actions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_tender_bid_actions_tender_id'), 'tender_bid_actions', ['tender_id'], unique=False)
    op.create_table('tender_requirement_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(length=80), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('relevance', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['company_evidence_documents.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['tender_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_requirement_evidence_document_id'), 'tender_requirement_evidence', ['document_id'], unique=False)
    op.create_index(op.f('ix_tender_requirement_evidence_requirement_id'), 'tender_requirement_evidence', ['requirement_id'], unique=False)
    op.create_table('tender_requirement_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('match_status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('company_field', sa.String(length=80), nullable=True),
    sa.Column('company_value', sa.Text(), nullable=True),
    sa.Column('company_explanation', sa.Text(), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.Column('evidence_document_count', sa.Integer(), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['tender_assessments.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['tender_requirements.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_requirement_matches_assessment_id'), 'tender_requirement_matches', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_tender_requirement_matches_tender_id'), 'tender_requirement_matches', ['tender_id'], unique=False)
    op.create_table('bid_document_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_document_id', sa.Integer(), nullable=False),
    sa.Column('evidence_document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bid_document_id'], ['bid_documents.id'], ),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['company_evidence_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_document_links_bid_document_id'), 'bid_document_links', ['bid_document_id'], unique=False)
    op.create_index(op.f('ix_bid_document_links_evidence_document_id'), 'bid_document_links', ['evidence_document_id'], unique=False)
    op.create_table('bid_package_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('readiness_state', sa.String(length=30), nullable=False),
    sa.Column('included_count', sa.Integer(), nullable=False),
    sa.Column('incomplete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['bid_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_package_exports_package_id'), 'bid_package_exports', ['package_id'], unique=False)
    op.create_table('bid_package_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('bid_document_id', sa.Integer(), nullable=True),
    sa.Column('evidence_document_id', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bid_document_id'], ['bid_documents.id'], ),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['company_evidence_documents.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['bid_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_package_items_package_id'), 'bid_package_items', ['package_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bid_package_items_package_id'), table_name='bid_package_items')
    op.drop_table('bid_package_items')
    op.drop_index(op.f('ix_bid_package_exports_package_id'), table_name='bid_package_exports')
    op.drop_table('bid_package_exports')
    op.drop_index(op.f('ix_bid_document_links_evidence_document_id'), table_name='bid_document_links')
    op.drop_index(op.f('ix_bid_document_links_bid_document_id'), table_name='bid_document_links')
    op.drop_table('bid_document_links')
    op.drop_index(op.f('ix_tender_requirement_matches_tender_id'), table_name='tender_requirement_matches')
    op.drop_index(op.f('ix_tender_requirement_matches_assessment_id'), table_name='tender_requirement_matches')
    op.drop_table('tender_requirement_matches')
    op.drop_index(op.f('ix_tender_requirement_evidence_requirement_id'), table_name='tender_requirement_evidence')
    op.drop_index(op.f('ix_tender_requirement_evidence_document_id'), table_name='tender_requirement_evidence')
    op.drop_table('tender_requirement_evidence')
    op.drop_index(op.f('ix_tender_bid_actions_tender_id'), table_name='tender_bid_actions')
    op.drop_index(op.f('ix_tender_bid_actions_assessment_id'), table_name='tender_bid_actions')
    op.drop_table('tender_bid_actions')
    op.drop_index(op.f('ix_bid_requirements_workspace_id'), table_name='bid_requirements')
    op.drop_table('bid_requirements')
    op.drop_index(op.f('ix_bid_packages_workspace_id'), table_name='bid_packages')
    op.drop_table('bid_packages')
    op.drop_index(op.f('ix_bid_notes_workspace_id'), table_name='bid_notes')
    op.drop_table('bid_notes')
    op.drop_index(op.f('ix_bid_documents_workspace_id'), table_name='bid_documents')
    op.drop_table('bid_documents')
    op.drop_index(op.f('ix_bid_clarifications_workspace_id'), table_name='bid_clarifications')
    op.drop_table('bid_clarifications')
    op.drop_index(op.f('ix_usage_events_workspace_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_user_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_tender_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_created_at'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_table('tender_sources')
    op.drop_table('tender_risks')
    op.drop_table('tender_requirements')
    op.drop_table('tender_questions')
    op.drop_table('tender_documents')
    op.drop_table('tender_dates')
    op.drop_index(op.f('ix_tender_checklist_items_tender_id'), table_name='tender_checklist_items')
    op.drop_table('tender_checklist_items')
    op.drop_index(op.f('ix_tender_assessments_tender_id'), table_name='tender_assessments')
    op.drop_table('tender_assessments')
    op.drop_index(op.f('ix_company_evidence_chunks_document_id'), table_name='company_evidence_chunks')
    op.drop_table('company_evidence_chunks')
    op.drop_index(op.f('ix_bid_workspaces_tender_id'), table_name='bid_workspaces')
    op.drop_table('bid_workspaces')
    op.drop_index(op.f('ix_tenders_workspace_id'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_company_profiles_workspace_id'), table_name='company_profiles')
    op.drop_table('company_profiles')
    op.drop_index(op.f('ix_company_evidence_documents_workspace_id'), table_name='company_evidence_documents')
    op.drop_table('company_evidence_documents')
    op.drop_index(op.f('ix_workspaces_user_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_provider_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_provider_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_billing_events_provider_event_id'), table_name='billing_events')
    op.drop_table('billing_events')
    # ### end Alembic commands ###
